### ISSUE TITLE
Feedback on the example running experience

### ISSUE THREAD

**Issue by equaeghe** [deeprob-org/deeprob-kit#11]
I ran all examples. They are a nice way of testing how the code runs on one's computer and show its capabilities. Below, I provide some points of feedback/suggestions that may improve the experience people have when running the examples. Some of that feedback may pertain or be relevant to other parts of the code base as well.

1. Often, files are created as part of an example, such as the nice illustrative figures. It would be useful to alert the user of all files being created, so that they are aware of this even if they do not keep an eye on their working folder. Also, some files have unclear purpose (such as the pt files). Clarifying their use when alerting they are created would therefore be useful. (If they are temporary files, delete them at the end of running the example or use the [tempfile](https://docs.python.org/3/library/tempfile.html) module.)
2. The console output provides useful information about the time it takes to run an example. If possible, generalize this to all examples that are not trivially short. (I think the first stage of `spn_latent_mnist.py` does not.)
3. The console output numerical values often have a large number of digits displayed. There is little reason to believe that many are actually significant. Furthermore, it makes the output more difficult to read and digest. Ideally, output only significant digits, but if you do not know how many digits are significant, 4 digits in total is a good upper bound (like 57.63 %, 1234, 1.234e6).
4. Many of the console output numbers have units (s, it/s, batch/s). The international standard is to always have a space between a number and its unit.
5. Sometimes, JSON output is created either as console output or in files. Try to pretty-print it a bit, to make it easier to scan. If it is not meant to be read, perhaps consider omitting it.
6. For many of the examples, you generate images, which is great. It would add value to have every example generate some image, even if it is not a sample. Namely, the examples can also provide users of the package inspiration of the type of images that they might generate.
7. In one case, an image was generated in an interactive window (`nvp1d_moons.py`) and not in an image file. That is nice. Could it be generalized to all examples, with a fallback to image file generation?
8. In two cases, the examples automatically downloaded some datasets. While convenient, some users might not expect this, may not like it, or may not have an internet connection. I think it would be more user-friendly to ask first or instruct first where to download the dataset. Furthermore, I saw that MNIST was downloaded from LeCunn's original website, who explicitly requests not to do that (*“Please refrain from accessing these files from automated scripts with high frequency. Make copies!”*); it would be polite to honor that request. In general, make sure to download from permanent repositories if possible instead of possibly non-permanent websites.
9. The console output lists accuracy percentages. These generally are quite a bit closer to 100 % than to 0 %. Therefore, the initial digit (7, 8, 9) is often not very significant and therefore distracting. It is more user friendly to use error rate instead, so, e.g., [12.49, 8.66, 4.57] instead of [87.51, 91.34, 95.43].

Obviously, these are mostly cosmetic suggestions, so I'd understand that you classify (parts of) this issue as ‘wontfix’.

**Comment by equaeghe** [comment]
* (2) I actually meant to also include a tqdm timer for the first stage of `spn_latent_mnist.py` if possible. It does a good job of estimating remaining and total time.
* (4) Ah, it seems it is on tqdm's developer's radar: https://github.com/tqdm/tqdm/issues/825 and https://github.com/tqdm/tqdm/pull/1063
* (8) Ah, then this is an upstream issue: https://github.com/pytorch/vision/issues/4634
* (9) I do not understand why it is a constraint that some libraries return accuracies. Is adding a ‘one minus’ step not possible?

**Comment by loreloc** [comment]
2. Oh I misunderstood. Yes this can be done easily.
9. I think this would have sense only when printing the results.
